// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pw.Hub.Tracker.Infrastructure.Data;

#nullable disable

namespace Pw.Hub.Tracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260318163431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaBattleStats", b =>
                {
                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<short>("EntityType")
                        .HasColumnType("smallint");

                    b.Property<int>("MatchPattern")
                        .HasColumnType("integer");

                    b.Property<long?>("ArenaPlayerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ArenaTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("BattleCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("WeekBattleCount")
                        .HasColumnType("integer");

                    b.Property<int>("WeekMaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("WeekWinCount")
                        .HasColumnType("integer");

                    b.Property<int>("WinCount")
                        .HasColumnType("integer");

                    b.HasKey("EntityId", "EntityType", "MatchPattern");

                    b.HasIndex("ArenaPlayerId");

                    b.HasIndex("ArenaTeamId");

                    b.ToTable("arena_battle_stats", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LoserTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("MatchPattern")
                        .HasColumnType("integer");

                    b.Property<long?>("TeamAId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TeamAScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamAScoreBefore")
                        .HasColumnType("integer");

                    b.Property<long?>("TeamBId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TeamBScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamBScoreBefore")
                        .HasColumnType("integer");

                    b.Property<long?>("WinnerTeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("arena_matches", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatchParticipant", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerCls")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreBefore")
                        .HasColumnType("integer");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchId", "TeamId");

                    b.ToTable("arena_match_participants", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Cls")
                        .HasColumnType("integer");

                    b.Property<long>("LastBattleTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("LastVisiteTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("RewardMoney")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeekResetTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("arena_players", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaScoreHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("BattleCount")
                        .HasColumnType("integer");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<short>("EntityType")
                        .HasColumnType("smallint");

                    b.Property<int>("MatchPattern")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("WinCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "EntityType", "MatchPattern", "RecordedAt");

                    b.ToTable("arena_score_history", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CaptainId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastVisiteTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeekResetTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("arena_teams", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeamMember", b =>
                {
                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RewardMoneyInfo")
                        .HasColumnType("bigint");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("arena_team_members", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaBattleStats", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", null)
                        .WithMany("BattleStats")
                        .HasForeignKey("ArenaPlayerId");

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", null)
                        .WithMany("BattleStats")
                        .HasForeignKey("ArenaTeamId");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId");

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatchParticipant", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeamMember", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", b =>
                {
                    b.Navigation("BattleStats");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", b =>
                {
                    b.Navigation("BattleStats");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
