// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pw.Hub.Tracker.Infrastructure.Data;

#nullable disable

namespace Pw.Hub.Tracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260331153437_AddOriginalMatchId")]
    partial class AddOriginalMatchId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaBattleStats", b =>
                {
                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Server")
                        .HasColumnType("text");

                    b.Property<short>("EntityType")
                        .HasColumnType("smallint");

                    b.Property<int>("MatchPattern")
                        .HasColumnType("integer");

                    b.Property<long?>("ArenaPlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ArenaPlayerPlayerServer")
                        .HasColumnType("text");

                    b.Property<long?>("ArenaTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("BattleCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("WeekBattleCount")
                        .HasColumnType("integer");

                    b.Property<int>("WeekMaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("WeekWinCount")
                        .HasColumnType("integer");

                    b.Property<int>("WinCount")
                        .HasColumnType("integer");

                    b.HasKey("EntityId", "Server", "EntityType", "MatchPattern");

                    b.HasIndex("ArenaTeamId");

                    b.HasIndex("ArenaPlayerId", "ArenaPlayerPlayerServer");

                    b.ToTable("arena_battle_stats", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LoserTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("MatchPattern")
                        .HasColumnType("integer");

                    b.Property<long?>("OriginalMatchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamAId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TeamAScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamAScoreBefore")
                        .HasColumnType("integer");

                    b.Property<long?>("TeamBId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TeamBScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamBScoreBefore")
                        .HasColumnType("integer");

                    b.Property<long?>("WinnerTeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OriginalMatchId")
                        .HasFilter("\"OriginalMatchId\" IS NOT NULL");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("arena_matches", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatchParticipant", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerCls")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreBefore")
                        .HasColumnType("integer");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchId", "TeamId");

                    b.HasIndex("PlayerId", "PlayerServer");

                    b.ToTable("arena_match_participants", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerServer")
                        .HasColumnType("text");

                    b.Property<long>("LastBattleTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("LastVisiteTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("RewardMoney")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeekResetTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "PlayerServer");

                    b.HasIndex("TeamId");

                    b.ToTable("arena_players", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaScoreHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Server")
                        .HasColumnType("text");

                    b.Property<int>("BattleCount")
                        .HasColumnType("integer");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<short>("EntityType")
                        .HasColumnType("smallint");

                    b.Property<int>("MatchPattern")
                        .HasColumnType("integer");

                    b.Property<int?>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("WinCount")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Server");

                    b.HasIndex("EntityId", "Server", "EntityType", "MatchPattern", "RecordedAt");

                    b.ToTable("arena_score_history", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CaptainId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastVisiteTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeekResetTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("arena_teams", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeamMember", b =>
                {
                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerServer")
                        .HasColumnType("text");

                    b.Property<long>("RewardMoneyInfo")
                        .HasColumnType("bigint");

                    b.HasKey("TeamId", "PlayerId", "PlayerServer");

                    b.HasIndex("PlayerId", "PlayerServer");

                    b.ToTable("arena_team_members", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Server")
                        .HasColumnType("text");

                    b.Property<int>("Cls")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "Server");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.PlayerProperty", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Server")
                        .HasColumnType("text");

                    b.Property<int>("AntiDefenseDegree")
                        .HasColumnType("integer");

                    b.Property<int>("AntiInvisibleDegree")
                        .HasColumnType("integer");

                    b.Property<int>("AntiResistanceDegree")
                        .HasColumnType("integer");

                    b.Property<long>("Armor")
                        .HasColumnType("bigint");

                    b.Property<long>("Attack")
                        .HasColumnType("bigint");

                    b.Property<int>("AttackDegree")
                        .HasColumnType("integer");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("CritDamageBonus")
                        .HasColumnType("integer");

                    b.Property<int>("CritRate")
                        .HasColumnType("integer");

                    b.Property<long>("DamageHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageLow")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageMagicHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageMagicLow")
                        .HasColumnType("bigint");

                    b.Property<int>("DamageReduce")
                        .HasColumnType("integer");

                    b.Property<int>("DefendDegree")
                        .HasColumnType("integer");

                    b.Property<long>("Defense")
                        .HasColumnType("bigint");

                    b.Property<long>("Hp")
                        .HasColumnType("bigint");

                    b.Property<int>("InvisibleDegree")
                        .HasColumnType("integer");

                    b.Property<long>("Mp")
                        .HasColumnType("bigint");

                    b.Property<int>("PeakGrade")
                        .HasColumnType("integer");

                    b.Property<int>("Prayspeed")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<long[]>("Resistance")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<double>("RunSpeed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Vigour")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "Server");

                    b.ToTable("player_properties", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.PlayerPropertyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("AntiDefenseDegree")
                        .HasColumnType("integer");

                    b.Property<int>("AntiInvisibleDegree")
                        .HasColumnType("integer");

                    b.Property<int>("AntiResistanceDegree")
                        .HasColumnType("integer");

                    b.Property<long>("Armor")
                        .HasColumnType("bigint");

                    b.Property<long>("Attack")
                        .HasColumnType("bigint");

                    b.Property<int>("AttackDegree")
                        .HasColumnType("integer");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("CritDamageBonus")
                        .HasColumnType("integer");

                    b.Property<int>("CritRate")
                        .HasColumnType("integer");

                    b.Property<long>("DamageHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageLow")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageMagicHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageMagicLow")
                        .HasColumnType("bigint");

                    b.Property<int>("DamageReduce")
                        .HasColumnType("integer");

                    b.Property<int>("DefendDegree")
                        .HasColumnType("integer");

                    b.Property<long>("Defense")
                        .HasColumnType("bigint");

                    b.Property<long>("Hp")
                        .HasColumnType("bigint");

                    b.Property<int>("InvisibleDegree")
                        .HasColumnType("integer");

                    b.Property<long>("Mp")
                        .HasColumnType("bigint");

                    b.Property<int>("PeakGrade")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Prayspeed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<long[]>("Resistance")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<double>("RunSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Vigour")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Server");

                    b.HasIndex("PlayerId", "Server", "RecordedAt");

                    b.ToTable("player_property_history", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaBattleStats", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", null)
                        .WithMany("BattleStats")
                        .HasForeignKey("ArenaTeamId");

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", null)
                        .WithMany("BattleStats")
                        .HasForeignKey("ArenaPlayerId", "ArenaPlayerPlayerServer");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", "OriginalMatch")
                        .WithMany()
                        .HasForeignKey("OriginalMatchId");

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId");

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId");

                    b.Navigation("OriginalMatch");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatchParticipant", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId", "PlayerServer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("Id", "PlayerServer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeamMember", b =>
                {
                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId", "PlayerServer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaMatch", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaPlayer", b =>
                {
                    b.Navigation("BattleStats");
                });

            modelBuilder.Entity("Pw.Hub.Tracker.Domain.Entities.ArenaTeam", b =>
                {
                    b.Navigation("BattleStats");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
